// Optional AI-backend provider.
//
// If you run a secure backend (e.g. the FastAPI example in README.md) that
// calls an AI API server-side, set VITE_AI_BACKEND_URL to its origin and this
// provider will be used instead of the on-device scheduler. Your API key stays
// on the server — it is never exposed in frontend code.
//
// Expected backend contract:
//   POST {base}/api/generate-plan
//   Body: { subjects, startDate, examDate, dailyHours }
//   Response: { tasks: [ { date, subjectId, subjectName, topicId, topicName,
//                         difficulty, priority, durationMin, activity,
//                         sessionLabel, reason } ] }

export const PROVIDER_ID = "ai-backend";
export const PROVIDER_LABEL = "AI backend";

const BASE_URL = import.meta.env?.VITE_AI_BACKEND_URL;

export function isConfigured() {
  return Boolean(BASE_URL);
}

function assertTask(t, i) {
  const required = ["date", "subjectName", "topicName", "durationMin", "activity", "reason"];
  for (const k of required) {
    if (t[k] === undefined || t[k] === null || t[k] === "") {
      throw new Error(`AI backend returned task #${i + 1} missing "${k}".`);
    }
  }
  if (!["Learn", "Practice", "Revision"].includes(t.activity)) {
    throw new Error(`AI backend returned task #${i + 1} with unknown activity "${t.activity}".`);
  }
}

export async function generate(input) {
  if (!isConfigured()) {
    throw new Error(
      "AI backend is not configured. Set VITE_AI_BACKEND_URL in your .env file " +
        "(see README.md), or continue with the on-device Smart Scheduler."
    );
  }
  let res;
  try {
    res = await fetch(`${BASE_URL.replace(/\/$/, "")}/api/generate-plan`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        subjects: input.subjects,
        startDate: input.startDate,
        examDate: input.examDate,
        dailyHours: input.dailyHours,
      }),
    });
  } catch (e) {
    throw new Error(`Could not reach the AI backend at ${BASE_URL}. Is it running?`);
  }
  if (!res.ok) {
    throw new Error(`AI backend returned HTTP ${res.status}. Check the server logs.`);
  }
  const data = await res.json();
  if (!Array.isArray(data.tasks) || data.tasks.length === 0) {
    throw new Error("AI backend returned no tasks.");
  }
  data.tasks.forEach(assertTask);
  const tasks = data.tasks.map((t, i) => ({
    id: `ai_${Date.now().toString(36)}_${i}`,
    completed: false,
    sessionLabel: t.sessionLabel || t.activity,
    ...t,
  }));
  tasks.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
  return {
    tasks,
    provider: PROVIDER_ID,
    providerLabel: PROVIDER_LABEL,
    stats: null,
    note: "Plan generated by your AI backend.",
  };
}
