import { useMemo } from "react";
import { Button, Badge, EmptyState } from "./ui.jsx";
import { formatShort, todayISO } from "../lib/dateUtils.js";

function TaskRow({ task, onToggle }) {
  return (
    <div className={`ff-task${task.completed ? " done" : ""}`}>
      <button
        className={`ff-check${task.completed ? " done" : ""}`}
        onClick={() => onToggle(task.id)}
        title={task.completed ? "Mark as not done" : "Mark as complete"}
      >
        {task.completed ? "✓" : ""}
      </button>
      <div className="ff-task-body">
        <div className="ff-task-top">
          <span className="ff-task-name">{task.topicName}</span>
          <Badge kind={task.activity.toLowerCase()}>{task.activity}</Badge>
          <Badge kind={task.difficulty.toLowerCase()}>{task.difficulty}</Badge>
          <Badge kind={task.priority.toLowerCase()}>{task.priority} priority</Badge>
        </div>
        <div className="ff-task-sub">
          {task.subjectName} · {task.sessionLabel} · {task.durationMin} min
        </div>
        <div className="ff-task-reason">{task.reason}</div>
      </div>
    </div>
  );
}

export default function PlanView({ plan, planMeta, dailyHours, onToggleTask, onFallingBehind, onEditSetup, onReset }) {
  const byDay = useMemo(() => {
    const map = new Map();
    for (const t of plan) {
      if (!map.has(t.date)) map.set(t.date, []);
      map.get(t.date).push(t);
    }
    return [...map.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1));
  }, [plan]);

  const dailyMin = Math.round(dailyHours * 60);
  const today = todayISO();

  if (!plan || plan.length === 0) {
    return (
      <EmptyState
        title="No study plan yet"
        body="Set up your subjects and generate a plan to see your schedule here."
        action={<Button onClick={onEditSetup}>Set up my plan</Button>}
      />
    );
  }

  return (
    <div>
      <div className="ff-toolbar">
        <div>
          <h2 className="ff-section-title" style={{ marginBottom: 2 }}>Your study plan</h2>
          <div className="ff-section-sub" style={{ margin: 0 }}>
            {planMeta?.providerLabel ? `Generated by ${planMeta.providerLabel}. ` : ""}
            Tap a checkbox when you finish a session.
          </div>
        </div>
        <div className="spacer" />
        <Button variant="secondary" size="small" onClick={onFallingBehind}>
          I'm Falling Behind
        </Button>
      </div>

      {planMeta?.stats?.tight && (
        <div className="ff-result-note" style={{ background: "#f6e3dc", borderColor: "#e8c9bd", marginBottom: 16 }}>
          ⚠️ This plan needs more time than your daily {dailyHours}h allows. Days marked in red
          exceed your budget — consider adding study hours or trimming topics.
        </div>
      )}

      {byDay.map(([date, tasks]) => {
        const mins = tasks.reduce((s, t) => s + t.durationMin, 0);
        const done = tasks.filter((t) => t.completed).length;
        const over = mins > dailyMin;
        const isToday = date === today;
        return (
          <div key={date} className={`ff-day${over ? " over" : ""}`}>
            <div className="ff-day-head">
              <div>
                <span className="ff-day-title">
                  {isToday ? "Today" : formatShort(date)}
                </span>{" "}
                <span className="ff-day-date">{isToday ? `· ${formatShort(date)}` : ""}</span>
              </div>
              <span className="ff-day-total">
                {done}/{tasks.length} done · {Math.floor(mins / 60)}h {mins % 60}m
                {over ? " — over budget" : ""}
              </span>
            </div>
            {tasks.map((t) => (
              <TaskRow key={t.id} task={t} onToggle={onToggleTask} />
            ))}
          </div>
        );
      })}

      <div className="ff-toolbar" style={{ marginTop: 28 }}>
        <Button variant="secondary" size="small" onClick={onEditSetup}>Edit setup</Button>
        <div className="spacer" />
        <Button variant="ghost" size="small" onClick={onReset}>Start over</Button>
      </div>
    </div>
  );
}
