import { useState } from "react";
import { Button, Card, Field } from "./ui.jsx";
import { todayISO, addDays } from "../lib/dateUtils.js";
import { activeProviderLabel } from "../providers/index.js";

let n = 0;
const uid = (p) => `${p}_${Date.now().toString(36)}_${n++}`;

const blankTopic = () => ({ id: uid("topic"), name: "", difficulty: "Medium", priority: "Medium" });
const blankSubject = () => ({ id: uid("subj"), name: "", topics: [blankTopic()] });

const DIFFS = ["Easy", "Medium", "Hard"];
const PRIS = ["Low", "Medium", "High"];

function SubjectEditor({ subject, onChange, onRemove, canRemove }) {
  const updateTopic = (topicId, patch) => {
    onChange({
      ...subject,
      topics: subject.topics.map((t) => (t.id === topicId ? { ...t, ...patch } : t)),
    });
  };
  const removeTopic = (topicId) => {
    if (subject.topics.length <= 1) return;
    onChange({ ...subject, topics: subject.topics.filter((t) => t.id !== topicId) });
  };

  return (
    <div className="ff-subject">
      <div className="ff-subject-head">
        <input
          className="ff-input"
          placeholder="Subject name — e.g. Data Structures"
          value={subject.name}
          onChange={(e) => onChange({ ...subject, name: e.target.value })}
        />
        {canRemove && (
          <button className="ff-icon-btn" title="Remove subject" onClick={onRemove}>×</button>
        )}
      </div>

      <div className="ff-label" style={{ marginBottom: 8 }}>Topics</div>
      {subject.topics.map((t) => (
        <div className="ff-topic-row" key={t.id}>
          <input
            className="ff-input"
            placeholder="Topic — e.g. Linked Lists"
            value={t.name}
            onChange={(e) => updateTopic(t.id, { name: e.target.value })}
          />
          <select
            className="ff-select"
            value={t.difficulty}
            onChange={(e) => updateTopic(t.id, { difficulty: e.target.value })}
            title="Difficulty"
          >
            {DIFFS.map((d) => <option key={d} value={d}>{d}</option>)}
          </select>
          <select
            className="ff-select ff-priority-col"
            value={t.priority}
            onChange={(e) => updateTopic(t.id, { priority: e.target.value })}
            title="Priority"
          >
            {PRIS.map((p) => <option key={p} value={p}>{p}</option>)}
          </select>
          <button className="ff-icon-btn" title="Remove topic" onClick={() => removeTopic(t.id)}>×</button>
        </div>
      ))}
      <button className="ff-add-link" onClick={() => onChange({ ...subject, topics: [...subject.topics, blankTopic()] })}>
        + Add topic
      </button>
    </div>
  );
}

export default function SetupForm({ initial, onGenerate, generating, error }) {
  const [profile, setProfile] = useState(() => ({
    startDate: initial?.profile?.startDate || todayISO(),
    examDate: initial?.profile?.examDate || addDays(todayISO(), 14),
    dailyHours: initial?.profile?.dailyHours ?? 3,
  }));
  const [subjects, setSubjects] = useState(() =>
    initial?.subjects?.length ? initial.subjects : [blankSubject()]
  );

  const updateSubject = (id, next) =>
    setSubjects((ss) => ss.map((s) => (s.id === id ? next : s)));

  const handleGenerate = () => {
    onGenerate({ profile, subjects });
  };

  return (
    <div>
      <h2 className="ff-section-title">Set up your study plan</h2>
      <p className="ff-section-sub">
        Add your subjects and topics, then tell us how much time you have.
      </p>

      <div className="ff-provider-note">
        <span>ℹ️</span>
        <span>
          Plans are generated by the <strong>{activeProviderLabel()}</strong>.{" "}
          {activeProviderLabel().includes("on-device")
            ? "It runs entirely in your browser — no AI API call is made, and nothing is faked."
            : "It calls your configured AI backend (your API key stays on the server)."}
        </span>
      </div>

      <Card style={{ marginBottom: 18 }}>
        <div className="ff-grid-3">
          <Field label="Start date">
            <input
              type="date"
              className="ff-input"
              value={profile.startDate}
              onChange={(e) => setProfile({ ...profile, startDate: e.target.value })}
            />
          </Field>
          <Field label="Exam date">
            <input
              type="date"
              className="ff-input"
              value={profile.examDate}
              min={profile.startDate}
              onChange={(e) => setProfile({ ...profile, examDate: e.target.value })}
            />
          </Field>
          <Field label="Daily study hours" hint="How many hours can you study per day?">
            <input
              type="number"
              className="ff-input"
              min="0.5"
              max="14"
              step="0.5"
              value={profile.dailyHours}
              onChange={(e) => setProfile({ ...profile, dailyHours: Number(e.target.value) })}
            />
          </Field>
        </div>
      </Card>

      {subjects.map((s) => (
        <SubjectEditor
          key={s.id}
          subject={s}
          onChange={(next) => updateSubject(s.id, next)}
          onRemove={() => setSubjects((ss) => ss.filter((x) => x.id !== s.id))}
          canRemove={subjects.length > 1}
        />
      ))}

      <button className="ff-add-link" onClick={() => setSubjects((ss) => [...ss, blankSubject()])} style={{ marginBottom: 18 }}>
        + Add subject
      </button>

      {error && <div className="ff-error" style={{ marginBottom: 12 }}>{error}</div>}

      <Button block onClick={handleGenerate} disabled={generating}>
        {generating ? "Building your plan…" : "Generate Study Plan"}
      </Button>
      <p className="ff-hint" style={{ textAlign: "center", marginTop: 10 }}>
        Takes a few seconds. Your plan is saved in this browser automatically.
      </p>
    </div>
  );
}
